# fly.toml app configuration file generated for portcullis-app on 2024-10-25T23:30:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portcullis-app'
primary_region = 'atl'

[build.args]
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY='pk_test_d2VsY29tZWQtYm94ZXItNTMuY2xlcmsuYWNjb3VudHMuZGV2JA'
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL='/'
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL='/onboarding'
  NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL='/create-organization'
  NEXT_PUBLIC_SUPABASE_URL='https://wwsbfcvfmmlvmdlhzadc.supabase.co'
  NEXT_PUBLIC_SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3c2JmY3ZmbW1sdm1kbGh6YWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc0MzU0NjcsImV4cCI6MjA0MzAxMTQ2N30.0QQBBzMbmU_BU8s_TzlvknCtOWAiX2KAAWuaOs0Rf2c'
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Main service for Next.js
[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [[services.ports]]
    port = 80
    handlers = ["http"]

# Inngest service
[[services]]
  protocol = "tcp"
  internal_port = 8288
  processes = ["app"]
  
  [[services.ports]]
    port = 8288
    handlers = ["tls", "http"]

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[env]
  INNGEST_SERVE_HOST = "https://portcullis-app.fly.dev"